<?php /**************** Copyright notice ************************
 *  (c) 2011 Simon Eric Scholl <simon@sdscholl.de>
 *  All rights reserved
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 ***************************************************************/

class SScholl_Books_Model_Book_List_Languagecode
	extends Varien_Object
{

	public function getAllOptions()
	{
		return $this->_options;
	}
	
    public function getOption($option)
    {
        return $this->_options[$option];
    }

	protected $_options = array(
		'aar'	=>	'Afar', // MARKER
		'abk'	=>	'Abkhaz', // MARKER
		'ace'	=>	'Achinese', // MARKER
		'ach'	=>	'Acoli', // MARKER
		'ada'	=>	'Adangme', // MARKER
		'ady'	=>	'Adygei', // MARKER
		'afa'	=>	'Afro-Asiatic languages', //Collective name. MARKER
		'afh'	=>	'Afrihili', //Artificial language. MARKER
		'afr'	=>	'Afrikaans', // MARKER
		'ain'	=>	'Ainu', // MARKER
		'aka'	=>	'Akan', // MARKER
		'akk'	=>	'Akkadian', // MARKER
		'alb'	=>	'Albanian', // MARKER
		'ale'	=>	'Aleut', // MARKER
		'alg'	=>	'Algonquian languages', //Collective name. MARKER
		'alt'	=>	'Southern Altai', // MARKER
		'amh'	=>	'Amharic', // MARKER
		'ang'	=>	'English, Old (ca. 450-1100)', // MARKER
		'anp'	=>	'Angika', // MARKER
		'apa'	=>	'Apache languages', //Collective name. MARKER
		'ara'	=>	'Arabic', // MARKER
		'arc'	=>	'Official Aramaic; Imperial Aramaic (700-300 BCE)', // MARKER
		'arg'	=>	'Aragonese', // MARKER
		'arm'	=>	'Armenian', // MARKER
		'arn'	=>	'Mapudungun; Mapuche', // MARKER
		'arp'	=>	'Arapaho', // MARKER
		'art'	=>	'Artificial languages', //Collective name. MARKER
		'arw'	=>	'Arawak', // MARKER
		'asm'	=>	'Assamese', // MARKER
		'ast'	=>	'Asturian; Bable; Leonese; Asturleonese', // MARKER
		'ath'	=>	'Athapascan languages', //Collective name. MARKER
		'aus'	=>	'Australian languages', //Collective name. MARKER
		'ava'	=>	'Avaric', // MARKER
		'ave'	=>	'Avestan', // MARKER
		'awa'	=>	'Awadhi', // MARKER
		'aym'	=>	'Aymara', // MARKER
		'aze'	=>	'Azerbaijani', // MARKER
		'bad'	=>	'Banda languages', //Collective name. MARKER
		'bai'	=>	'Bamileke languages', //Collective name. MARKER
		'bak'	=>	'Bashkir', // MARKER
		'bal'	=>	'Baluchi', // MARKER
		'bam'	=>	'Bambara', // MARKER
		'ban'	=>	'Balinese', // MARKER
		'baq'	=>	'Basque', // MARKER
		'bas'	=>	'Basa', // MARKER
		'bat'	=>	'Baltic languages', //Collective name. MARKER
		'bej'	=>	'Beja; Bedawiyet', // MARKER
		'bel'	=>	'Belarusian', // MARKER
		'bem'	=>	'Bemba', // MARKER
		'ben'	=>	'Bengali', // MARKER
		'ber'	=>	'Berber languages', //Collective name. MARKER
		'bho'	=>	'Bhojpuri', // MARKER
		'bih'	=>	'Bihari languages', //Collective name. MARKER
		'bik'	=>	'Bikol', // MARKER
		'bin'	=>	'Bini; Edo', // MARKER
		'bis'	=>	'Bislama', // MARKER
		'bla'	=>	'Siksika', // MARKER
		'bnt'	=>	'Bantu languages', //Collective name. MARKER
		'bos'	=>	'Bosnian', // MARKER
		'bra'	=>	'Braj', // MARKER
		'bre'	=>	'Breton', // MARKER
		'btk'	=>	'Batak languages', //Collective name. MARKER
		'bua'	=>	'Buriat', // MARKER
		'bug'	=>	'Buginese', // MARKER
		'bul'	=>	'Bulgarian', // MARKER
		'bur'	=>	'Burmese', // MARKER
		'byn'	=>	'Blin; Bilin', // MARKER
		'cad'	=>	'Caddo', // MARKER
		'cai'	=>	'Central American Indian languages', //Collective name. MARKER
		'car'	=>	'Galibi Carib', // MARKER
		'cat'	=>	'Catalan', // MARKER
		'cau'	=>	'Caucasian languages', //Collective name. MARKER
		'ceb'	=>	'Cebuano', // MARKER
		'cel'	=>	'Celtic languages', //Collective name. MARKER
		'cha'	=>	'Chamorro', // MARKER
		'chb'	=>	'Chibcha', // MARKER
		'che'	=>	'Chechen', // MARKER
		'chg'	=>	'Chagatai', // MARKER
		'chi'	=>	'Chinese', // MARKER
		'chk'	=>	'Chuukese (Truk)', // MARKER
		'chm'	=>	'Mari', // MARKER
		'chn'	=>	'Chinook jargon', // MARKER
		'cho'	=>	'Choctaw', // MARKER
		'chp'	=>	'Chipewyan; Dene Suline', // MARKER
		'chr'	=>	'Cherokee', // MARKER
		'chu'	=>	'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', // MARKER
		'chv'	=>	'Chuvash', // MARKER
		'chy'	=>	'Cheyenne', // MARKER
		'cmc'	=>	'Chamic languages', //Collective name. MARKER
		'cop'	=>	'Coptic', // MARKER
		'cor'	=>	'Cornish', // MARKER
		'cos'	=>	'Corsican', // MARKER
		'cpe'	=>	'Creoles and pidgins, English-based', //Collective name. MARKER
		'cpf'	=>	'Creoles and pidgins, French-based', //Collective name. MARKER
		'cpp'	=>	'Creoles and pidgins, Portuguese-based', //Collective name. MARKER
		'cre'	=>	'Cree', // MARKER
		'crh'	=>	'Crimean Turkish; Crimean Tatar', // MARKER
		'crp'	=>	'Creoles and pidgins', //Collective name. MARKER
		'csb'	=>	'Kashubian', // MARKER
		'cus'	=>	'Cushitic languages', //Collective name. MARKER
		'cze'	=>	'Czech', // MARKER
		'dak'	=>	'Dakota', // MARKER
		'dan'	=>	'Danish', // MARKER
		'dar'	=>	'Dargwa', // MARKER
		'day'	=>	'Land Dayak languages', //Collective name. MARKER
		'del'	=>	'Delaware', // MARKER
		'den'	=>	'Slave (Athapascan)', // MARKER
		'dgr'	=>	'Dogrib', // MARKER
		'din'	=>	'Dinka', // MARKER
		'div'	=>	'Divehi; Dhivehi; Maldivian', // MARKER
		'doi'	=>	'Dogri', // MARKER
		'dra'	=>	'Dravidian languages', //Collective name. MARKER
		'dsb'	=>	'Lower Sorbian', // MARKER
		'dua'	=>	'Duala', // MARKER
		'dum'	=>	'Dutch, Middle (ca. 1050-1350)', // MARKER
		'dut'	=>	'Dutch; Flemish', // MARKER
		'dyu'	=>	'Dyula', // MARKER
		'dzo'	=>	'Dzongkha', // MARKER
		'efi'	=>	'Efik', // MARKER
		'egy'	=>	'Egyptian (Ancient)', // MARKER
		'eka'	=>	'Ekajuk', // MARKER
		'elx'	=>	'Elamite', // MARKER
		'eng'	=>	'English', // MARKER
		'enm'	=>	'English, Middle (1100-1500)', // MARKER
		'epo'	=>	'Esperanto', //Artificial language. MARKER
		'est'	=>	'Estonian', // MARKER
		'ewe'	=>	'Ewe', // MARKER
		'ewo'	=>	'Ewondo', // MARKER
		'fan'	=>	'Fang', // MARKER
		'fao'	=>	'Faroese', // MARKER
		'fat'	=>	'Fanti', // MARKER
		'fij'	=>	'Fijian', // MARKER
		'fil'	=>	'Filipino; Pilipino', // MARKER
		'fin'	=>	'Finnish', // MARKER
		'fiu'	=>	'Finno-Ugrian languages', //Collective name. MARKER
		'fon'	=>	'Fon', // MARKER
		'fre'	=>	'French', // MARKER
		'frm'	=>	'French, Middle (ca. 1400-1600)', // MARKER
		'fro'	=>	'French, Old (ca. 842-1400)', // MARKER
		'frr'	=>	'Northern Frisian', // MARKER
		'frs'	=>	'Eastern Frisian', // MARKER
		'fry'	=>	'Western Frisian', // MARKER
		'ful'	=>	'Fulah', // MARKER
		'fur'	=>	'Friulian', // MARKER
		'gaa'	=>	'Gã', // MARKER
		'gay'	=>	'Gayo', // MARKER
		'gba'	=>	'Gbaya', // MARKER
		'gem'	=>	'Germanic languages', //Collective name. MARKER
		'geo'	=>	'Georgian', // MARKER
		'ger'	=>	'German', // MARKER
		'gez'	=>	'Ethiopic (Ge’ez)', // MARKER
		'gil'	=>	'Gilbertese', // MARKER
		'gla'	=>	'Scottish Gaelic', // MARKER
		'gle'	=>	'Irish', // MARKER
		'glg'	=>	'Galician', // MARKER
		'glv'	=>	'Manx', // MARKER
		'gmh'	=>	'German, Middle High (ca. 1050-1500)', // MARKER
		'goh'	=>	'German, Old High (ca. 750-1050)', // MARKER
		'gon'	=>	'Gondi', // MARKER
		'gor'	=>	'Gorontalo', // MARKER
		'got'	=>	'Gothic', // MARKER
		'grb'	=>	'Grebo', // MARKER
		'grc'	=>	'Greek, Ancient (to 1453)', // MARKER
		'gre'	=>	'Greek, Modern (1453-)', // MARKER
		'grn'	=>	'Guarani', // MARKER
		'gsw'	=>	'Swiss German; Alemannic', // MARKER
		'guj'	=>	'Gujarati', // MARKER
		'gwi'	=>	'Gwich’in', // MARKER
		'hai'	=>	'Haida', // MARKER
		'hat'	=>	'Haitian French Creole', // MARKER
		'hau'	=>	'Hausa', // MARKER
		'haw'	=>	'Hawaiian', // MARKER
		'heb'	=>	'Hebrew', // MARKER
		'her'	=>	'Herero', // MARKER
		'hil'	=>	'Hiligaynon', // MARKER
		'him'	=>	'Himachali languages; Western Pahari languages', //Collective name. MARKER
		'hin'	=>	'Hindi', // MARKER
		'hit'	=>	'Hittite', // MARKER
		'hmn'	=>	'Hmong; Mong', // MARKER
		'hmo'	=>	'Hiri Motu', // MARKER
		'hrv'	=>	'Croatian', // MARKER
		'hsb'	=>	'Upper Sorbian', // MARKER
		'hun'	=>	'Hungarian', // MARKER
		'hup'	=>	'Hupa', // MARKER
		'iba'	=>	'Iban', // MARKER
		'ibo'	=>	'Igbo', // MARKER
		'ice'	=>	'Icelandic', // MARKER
		'ido'	=>	'Ido', //Artificial language. MARKER
		'iii'	=>	'Sichuan Yi; Nuosu', // MARKER
		'ijo'	=>	'Ijo languages', //Collective name. MARKER
		'iku'	=>	'Inuktitut', // MARKER
		'ile'	=>	'Interlingue; Occidental', //Artificial language. MARKER
		'ilo'	=>	'Iloko', // MARKER
		'ina'	=>	'Interlingua (International Auxiliary Language Association)', //Artificial language. MARKER
		'inc'	=>	'Indic languages', //Collective name. MARKER
		'ind'	=>	'Indonesian', // MARKER
		'ine'	=>	'Indo-European languages', //Collective name. MARKER
		'inh'	=>	'Ingush', // MARKER
		'ipk'	=>	'Inupiaq', // MARKER
		'ira'	=>	'Iranian languages', //Collective name. MARKER
		'iro'	=>	'Iroquoian languages', //Collective name. MARKER
		'ita'	=>	'Italian', // MARKER
		'jav'	=>	'Javanese', // MARKER
		'jbo'	=>	'Lojban', // MARKER
		'jpn'	=>	'Japanese', // MARKER
		'jpr'	=>	'Judeo-Persian', // MARKER
		'jrb'	=>	'Judeo-Arabic', // MARKER
		'kaa'	=>	'Kara-Kalpak', // MARKER
		'kab'	=>	'Kabyle', // MARKER
		'kac'	=>	'Kachin; Jingpho', // MARKER
		'kal'	=>	'Kalâtdlisut; Greenlandic', // MARKER
		'kam'	=>	'Kamba', // MARKER
		'kan'	=>	'Kannada', // MARKER
		'kar'	=>	'Karen languages', //Collective name. MARKER
		'kas'	=>	'Kashmiri', // MARKER
		'kau'	=>	'Kanuri', // MARKER
		'kaw'	=>	'Kawi', // MARKER
		'kaz'	=>	'Kazakh', // MARKER
		'kbd'	=>	'Kabardian (Circassian)', // MARKER
		'kha'	=>	'Khasi', // MARKER
		'khi'	=>	'Khoisan languages', //Collective name. MARKER
		'khm'	=>	'Central Khmer', // MARKER
		'kho'	=>	'Khotanese; Sakan', // MARKER
		'kik'	=>	'Kikuyu; Gikuyu', // MARKER
		'kin'	=>	'Kinyarwanda', // MARKER
		'kir'	=>	'Kirghiz; Kyrgyz', // MARKER
		'kmb'	=>	'Kimbundu', // MARKER
		'kok'	=>	'Konkani', // MARKER
		'kom'	=>	'Komi', // MARKER
		'kon'	=>	'Kongo', // MARKER
		'kor'	=>	'Korean', // MARKER
		'kos'	=>	'Kusaiean (Caroline Islands)', // MARKER
		'kpe'	=>	'Kpelle', // MARKER
		'krc'	=>	'Karachay-Balkar', // MARKER
		'krl'	=>	'Karelian', // MARKER
		'kro'	=>	'Kru languages', //Collective name. MARKER
		'kru'	=>	'Kurukh', // MARKER
		'kua'	=>	'Kuanyama', // MARKER
		'kum'	=>	'Kumyk', // MARKER
		'kur'	=>	'Kurdish', // MARKER
		'kut'	=>	'Kutenai', // MARKER
		'lad'	=>	'Ladino', // MARKER
		'lah'	=>	'Lahnda', // MARKER
		'lam'	=>	'Lamba', // MARKER
		'lao'	=>	'Lao', // MARKER
		'lat'	=>	'Latin', // MARKER
		'lav'	=>	'Latvian', // MARKER
		'lez'	=>	'Lezgian', // MARKER
		'lim'	=>	'Limburgish', // MARKER
		'lin'	=>	'Lingala', // MARKER
		'lit'	=>	'Lithuanian', // MARKER
		'lol'	=>	'Mongo-Nkundu', // MARKER
		'loz'	=>	'Lozi', // MARKER
		'ltz'	=>	'Luxembourgish; Letzeburgesch', // MARKER
		'lua'	=>	'Luba-Lulua', // MARKER
		'lub'	=>	'Luba-Katanga', // MARKER
		'lug'	=>	'Ganda', // MARKER
		'lui'	=>	'Luiseño', // MARKER
		'lun'	=>	'Lunda', // MARKER
		'luo'	=>	'Luo (Kenya and Tanzania)', // MARKER
		'lus'	=>	'Lushai', // MARKER
		'mac'	=>	'Macedonian', // MARKER
		'mad'	=>	'Madurese', // MARKER
		'mag'	=>	'Magahi', // MARKER
		'mah'	=>	'Marshallese', // MARKER
		'mai'	=>	'Maithili', // MARKER
		'mak'	=>	'Makasar', // MARKER
		'mal'	=>	'Malayalam', // MARKER
		'man'	=>	'Mandingo', // MARKER
		'mao'	=>	'Maori', // MARKER
		'map'	=>	'Austronesian languages', //Collective name. MARKER
		'mar'	=>	'Marathi', // MARKER
		'mas'	=>	'Masai', // MARKER
		'may'	=>	'Malay', // MARKER
		'mdf'	=>	'Moksha', // MARKER
		'mdr'	=>	'Mandar', // MARKER
		'men'	=>	'Mende', // MARKER
		'mga'	=>	'Irish, Middle (ca. 1100-1550)', // MARKER
		'mic'	=>	'Mi’kmaq; Micmac', // MARKER
		'min'	=>	'Minangkabau', // MARKER
		'mis'	=>	'Uncoded languages', // MARKER
		'mkh'	=>	'Mon-Khmer languages', //Collective name. MARKER
		'mlg'	=>	'Malagasy', // MARKER
		'mlt'	=>	'Maltese', // MARKER
		'mnc'	=>	'Manchu', // MARKER
		'mni'	=>	'Manipuri', // MARKER
		'mno'	=>	'Manobo languages', //Collective name. MARKER
		'moh'	=>	'Mohawk', // MARKER
		'mol'	=>	'Moldavian; Moldovan', //DEPRECATED – use rum. MARKER
		'mon'	=>	'Mongolian', // MARKER
		'mos'	=>	'Mooré; Mossi', // MARKER
		'mul'	=>	'Multiple languages', // MARKER
		'mun'	=>	'Munda languages', //Collective name. MARKER
		'mus'	=>	'Creek', // MARKER
		'mwl'	=>	'Mirandese', // MARKER
		'mwr'	=>	'Marwari', // MARKER
		'myn'	=>	'Mayan languages', //Collective name. MARKER
		'myv'	=>	'Erzya', // MARKER
		'nah'	=>	'Nahuatl languages', //Collective name. MARKER
		'nai'	=>	'North American Indian languages', //Collective name. MARKER
		'nap'	=>	'Neapolitan', // MARKER
		'nau'	=>	'Nauruan', // MARKER
		'nav'	=>	'Navajo', // MARKER
		'nbl'	=>	'Ndebele, South', // MARKER
		'nde'	=>	'Ndebele, North', // MARKER
		'ndo'	=>	'Ndonga', // MARKER
		'nds'	=>	'Low German; Low Saxon', // MARKER
		'nep'	=>	'Nepali', // MARKER
		'new'	=>	'Newari; Nepal Bhasa', // MARKER
		'nia'	=>	'Nias', // MARKER
		'nic'	=>	'Niger-Kordofanian languages', //Collective name. MARKER
		'niu'	=>	'Niuean', // MARKER
		'nno'	=>	'Norwegian Nynorsk', // MARKER
		'nob'	=>	'Norwegian Bokmål', // MARKER
		'nog'	=>	'Nogai', // MARKER
		'non'	=>	'Old Norse', // MARKER
		'nor'	=>	'Norwegian', // MARKER
		'nqo'	=>	'N’Ko', // MARKER
		'nso'	=>	'Pedi; Sepedi; Northern Sotho', // MARKER
		'nub'	=>	'Nubian languages', //Collective name. MARKER
		'nwc'	=>	'Classical Newari; Old Newari; Classical Nepal Bhasa', // MARKER
		'nya'	=>	'Chichewa; Chewa; Nyanja', // MARKER
		'nym'	=>	'Nyamwezi', // MARKER
		'nyn'	=>	'Nyankole', // MARKER
		'nyo'	=>	'Nyoro', // MARKER
		'nzi'	=>	'Nzima', // MARKER
		'oci'	=>	'Occitan (post 1500)', // MARKER
		'oji'	=>	'Ojibwa', // MARKER
		'ori'	=>	'Oriya', // MARKER
		'orm'	=>	'Oromo', // MARKER
		'osa'	=>	'Osage', // MARKER
		'oss'	=>	'Ossetian; Ossetic', // MARKER
		'ota'	=>	'Turkish, Ottoman', // MARKER
		'oto'	=>	'Otomian languages', //Collective name. MARKER
		'paa'	=>	'Papuan languages', //Collective name. MARKER
		'pag'	=>	'Pangasinan', // MARKER
		'pal'	=>	'Pahlavi', // MARKER
		'pam'	=>	'Pampanga; Kapampangan', // MARKER
		'pan'	=>	'Panjabi', // MARKER
		'pap'	=>	'Papiamento', // MARKER
		'pau'	=>	'Palauan', // MARKER
		'peo'	=>	'Old Persian (ca. 600-400 B.C.)', // MARKER
		'per'	=>	'Persian', // MARKER
		'phi'	=>	'Philippine languages', //Collective name. MARKER
		'phn'	=>	'Phoenician', // MARKER
		'pli'	=>	'Pali', // MARKER
		'pol'	=>	'Polish', // MARKER
		'pon'	=>	'Ponapeian', // MARKER
		'por'	=>	'Portuguese', // MARKER
		'pra'	=>	'Prakrit languages', //Collective name. MARKER
		'pro'	=>	'Provençal, Old (to 1500); Occitan, Old (to 1500)', // MARKER
		'pus'	=>	'Pushto; Pashto', // MARKER
		'qar'	=>	'Aranés', //ONIX local code. MARKER
		'qav'	=>	'Valencian', //ONIX local code. MARKER
		'que'	=>	'Quechua', // MARKER
		'raj'	=>	'Rajasthani', // MARKER
		'rap'	=>	'Rapanui', // MARKER
		'rar'	=>	'Rarotongan; Cook Islands Maori', // MARKER
		'roa'	=>	'Romance languages', //Collective name. MARKER
		'roh'	=>	'Romansh', // MARKER
		'rom'	=>	'Romany', // MARKER
		'rum'	=>	'Romanian', // MARKER
		'run'	=>	'Rundi', // MARKER
		'rup'	=>	'Aromanian; Arumanian; Macedo-Romanian', // MARKER
		'rus'	=>	'Russian', // MARKER
		'sad'	=>	'Sandawe', // MARKER
		'sag'	=>	'Sango', // MARKER
		'sah'	=>	'Yakut', // MARKER
		'sai'	=>	'South American Indian languages', //Collective name. MARKER
		'sal'	=>	'Salishan languages', //Collective name. MARKER
		'sam'	=>	'Samaritan Aramaic', // MARKER
		'san'	=>	'Sanskrit', // MARKER
		'sas'	=>	'Sasak', // MARKER
		'sat'	=>	'Santali', // MARKER
		'scc'	=>	'Serbian', //DEPRECATED – use srp. MARKER
		'scn'	=>	'Sicilian', // MARKER
		'sco'	=>	'Scots (lallans)', // MARKER
		'scr'	=>	'Croatian', //DEPRECATED – use hrv. MARKER
		'sel'	=>	'Selkup', // MARKER
		'sem'	=>	'Semitic languages', //Collective name. MARKER
		'sga'	=>	'Irish, Old (to 1100)', // MARKER
		'sgn'	=>	'Sign languages', //Collective name. MARKER
		'shn'	=>	'Shan', // MARKER
		'sid'	=>	'Sidamo', // MARKER
		'sin'	=>	'Sinhala; Sinhalese', // MARKER
		'sio'	=>	'Siouan languages', //Collective name. MARKER
		'sit'	=>	'Sino-Tibetan languages', //Collective name. MARKER
		'sla'	=>	'Slavic languages', //Collective name. MARKER
		'slo'	=>	'Slovak', // MARKER
		'slv'	=>	'Slovenian', // MARKER
		'sma'	=>	'Southern Sami', // MARKER
		'sme'	=>	'Northern Sami', // MARKER
		'smi'	=>	'Sami languages', //Collective name. MARKER
		'smj'	=>	'Lule Sami', // MARKER
		'smn'	=>	'Inari Sami', // MARKER
		'smo'	=>	'Samoan', // MARKER
		'sms'	=>	'Skolt Sami', // MARKER
		'sna'	=>	'Shona', // MARKER
		'snd'	=>	'Sindhi', // MARKER
		'snk'	=>	'Soninke', // MARKER
		'sog'	=>	'Sogdian', // MARKER
		'som'	=>	'Somali', // MARKER
		'son'	=>	'Songhai languages', //Collective name. MARKER
		'sot'	=>	'Sotho; Sesotho', // MARKER
		'spa'	=>	'Spanish', // MARKER
		'srd'	=>	'Sardinian', // MARKER
		'srn'	=>	'Sranan Tongo', // MARKER
		'srp'	=>	'Serbian', // MARKER
		'srr'	=>	'Serer', // MARKER
		'ssa'	=>	'Nilo-Saharan languages', //Collective name. MARKER
		'ssw'	=>	'Swazi; Swati', // MARKER
		'suk'	=>	'Sukuma', // MARKER
		'sun'	=>	'Sundanese', // MARKER
		'sus'	=>	'Susu', // MARKER
		'sux'	=>	'Sumerian', // MARKER
		'swa'	=>	'Swahili', // MARKER
		'swe'	=>	'Swedish', // MARKER
		'syc'	=>	'Classical Syriac', // MARKER
		'syr'	=>	'Syriac', // MARKER
		'tah'	=>	'Tahitian', // MARKER
		'tai'	=>	'Tai languages', //Collective name. MARKER
		'tam'	=>	'Tamil', // MARKER
		'tat'	=>	'Tatar', // MARKER
		'tel'	=>	'Telugu', // MARKER
		'tem'	=>	'Temne; Time', // MARKER
		'ter'	=>	'Terena', // MARKER
		'tet'	=>	'Tetum', // MARKER
		'tgk'	=>	'Tajik', // MARKER
		'tgl'	=>	'Tagalog', // MARKER
		'tha'	=>	'Thai', // MARKER
		'tib'	=>	'Tibetan', // MARKER
		'tig'	=>	'Tigré', // MARKER
		'tir'	=>	'Tigrinya', // MARKER
		'tiv'	=>	'Tiv', // MARKER
		'tkl'	=>	'Tokelauan', // MARKER
		'tlh'	=>	'Klingon; tlhIngan-Hol', //Artificial language. MARKER
		'tli'	=>	'Tlingit', // MARKER
		'tmh'	=>	'Tamashek', // MARKER
		'tog'	=>	'Tonga (Nyasa)', // MARKER
		'ton'	=>	'Tongan', // MARKER
		'tpi'	=>	'Tok Pisin', // MARKER
		'tsi'	=>	'Tsimshian', // MARKER
		'tsn'	=>	'Tswana', //AKA Setswana. MARKER
		'tso'	=>	'Tsonga', // MARKER
		'tuk'	=>	'Turkmen', // MARKER
		'tum'	=>	'Tumbuka', // MARKER
		'tup'	=>	'Tupi languages', //Collective name. MARKER
		'tur'	=>	'Turkish', // MARKER
		'tut'	=>	'Altaic languages', // MARKER
		'tvl'	=>	'Tuvaluan', // MARKER
		'twi'	=>	'Twi', // MARKER
		'tyv'	=>	'Tuvinian', // MARKER
		'udm'	=>	'Udmurt', // MARKER
		'uga'	=>	'Ugaritic', // MARKER
		'uig'	=>	'Uighur; Uyghur', // MARKER
		'ukr'	=>	'Ukrainian', // MARKER
		'umb'	=>	'Umbundu', // MARKER
		'und'	=>	'Undetermined language', // MARKER
		'urd'	=>	'Urdu', // MARKER
		'uzb'	=>	'Uzbek', // MARKER
		'vai'	=>	'Vai', // MARKER
		'ven'	=>	'Venda', // MARKER
		'vie'	=>	'Vietnamese', // MARKER
		'vol'	=>	'Volapük', //Artificial language. MARKER
		'vot'	=>	'Votic', // MARKER
		'wak'	=>	'Wakashan languages', //Collective name. MARKER
		'wal'	=>	'Wolaitta; Wolaytta', // MARKER
		'war'	=>	'Waray', // MARKER
		'was'	=>	'Washo', // MARKER
		'wel'	=>	'Welsh', // MARKER
		'wen'	=>	'Sorbian languages', //Collective name. MARKER
		'wln'	=>	'Walloon', // MARKER
		'wol'	=>	'Wolof', // MARKER
		'xal'	=>	'Kalmyk', // MARKER
		'xho'	=>	'Xhosa', // MARKER
		'yao'	=>	'Yao', // MARKER
		'yap'	=>	'Yapese', // MARKER
		'yid'	=>	'Yiddish', // MARKER
		'yor'	=>	'Yoruba', // MARKER
		'ypk'	=>	'Yupik languages', //Collective name. MARKER
		'zap'	=>	'Zapotec', // MARKER
		'zbl'	=>	'Blissymbols; Blissymbolics; Bliss', //Artificial language. MARKER
		'zen'	=>	'Zenaga', // MARKER
		'zha'	=>	'Zhuang; Chuang', // MARKER
		'znd'	=>	'Zande languages', //Collective name. MARKER
		'zul'	=>	'Zulu', // MARKER
		'zun'	=>	'Zuni', // MARKER
		'zxx'	=>	'No linguistic content', // MARKER
		'zza'	=>	'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', // MARKER
	
	);

}